// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADufktrKm8zF3cnU-jSYfrDtZYvKl2V1I',
    appId: '1:7469976013:web:23e9b01546d12af3935c84',
    messagingSenderId: '7469976013',
    projectId: 'chatapp-db5e1',
    authDomain: 'chatapp-db5e1.firebaseapp.com',
    storageBucket: 'chatapp-db5e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuaB9ayXNq5weOS4zCm4Xev_m0MF_t7UU',
    appId: '1:7469976013:android:c6e194ee37a9c236935c84',
    messagingSenderId: '7469976013',
    projectId: 'chatapp-db5e1',
    storageBucket: 'chatapp-db5e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEP5JU0S7Kyz3c6mYNEOJT3REHTqRri44',
    appId: '1:7469976013:ios:59907f96271cb179935c84',
    messagingSenderId: '7469976013',
    projectId: 'chatapp-db5e1',
    storageBucket: 'chatapp-db5e1.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEP5JU0S7Kyz3c6mYNEOJT3REHTqRri44',
    appId: '1:7469976013:ios:44a758d6cba9594b935c84',
    messagingSenderId: '7469976013',
    projectId: 'chatapp-db5e1',
    storageBucket: 'chatapp-db5e1.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
